bootcamp/urls.py
from django.conf import settings
from django.conf.urls import include, url
from django.conf.urls.static import static
from django.contrib.auth import views as auth_views

from bootcamp.activities import views as activities_views
from bootcamp.authentication import views as bootcamp_auth_views
from bootcamp.core import views as core_views
from bootcamp.search import views as search_views
from django.contrib import admin
admin.autodiscover()
#from bootcamp.follow import views
#from bootcamp.core import views
#from pusherchat import views


urlpatterns = [
    url(r'^$', core_views.home, name='home'),
    url(r'^login', auth_views.login, {'template_name': 'core/cover.html'},
        name='login'),
    url(r'^logout', auth_views.logout, {'next_page': '/'}, name='logout'),
    url(r'^signup/$', bootcamp_auth_views.signup, name='signup'),
    url(r'^settings/$', core_views.settings, name='settings'),
    url(r'^settings/picture/$', core_views.picture, name='picture'),
    url(r'^settings/upload_picture/$', core_views.upload_picture,
        name='upload_picture'),
    url(r'^settings/save_uploaded_picture/$', core_views.save_uploaded_picture,
        name='save_uploaded_picture'),

    url(r'^settings/coverpicture/$', core_views.coverpicture, name='coverpicture'),
    url(r'^settings/cover_upload_picture/$', core_views.cover_upload_picture,
        name='cover_upload_picture'),
    url(r'^settings/save_cover_uploaded_picture/$', core_views.save_cover_uploaded_picture,
        name='save_cover_uploaded_picture'),

    url(r'^admin/', include(admin.site.urls)),

    url(r'^settings/password/$', core_views.password, name='password'),
    url(r'^network/$', core_views.network, name='network'),
    url(r'^feeds/', include('bootcamp.feeds.urls')),
    url(r'^questions/', include('bootcamp.questions.urls')),
    url(r'^articles/', include('bootcamp.articles.urls')),
    url(r'^messages/', include('bootcamp.messenger.urls')),
    url(r'^notifications/$', activities_views.notifications,
        name='notifications'),
    url(r'^notifications/last/$', activities_views.last_notifications,
        name='last_notifications'),
    url(r'^notifications/check/$', activities_views.check_notifications,
        name='check_notifications'),
    url(r'^search/$', search_views.search, name='search'),
    url(r'^contact/$', core_views.contact, name='contact'),
    url(r'^email/$', core_views.email, name='email'),
    url(r'^thanks/$', core_views.thanks, name='thanks'),
    url(r'^thanksinvite/$', core_views.thanksinvite, name='thanksinvite'),
    url(r'^thankyou/$', core_views.thankyou, name='thankyou'),
    url(r'^thankyouinvite/$', core_views.thankyouinvite, name='thankyouinvite'),
    #url(r'^archives/$', core_views.archives, name='archives'),
    url(r'^trending/$', core_views.trending, name='trending'),
    url(r'^news/$', core_views.news, name='news'),
     url(r'^newsfeed/$', core_views.newsfeed, name='newsfeed'),
    url(r'^postcrawler/$', core_views.postcrawler, name='postcrawler'),
    url(r'^searchcrawler/$', core_views.searchcrawler, name='searchcrawler'),
    url(r'^follow/(?P<user_profile_id>[^/]+)/$', core_views.follow_user, name='profile'),

    url(r'^chat/$', core_views.chat, name='chat'),
    #url(r'^ajax/chat/$', core_views.broadcast, name='broadcast'),

    url(r'^(?P<username>[^/]+)/$', core_views.profile, name='profile'),
    url(r'^i18n/', include('django.conf.urls.i18n', namespace='i18n')),




    #url(r'^follow/', include('bootcamp.follow.urls')),
    #url(r'^admin/', admin.site.urls),
    #url(r'^settings/forgotpassword/$', core_views.forgotpassword, name='forgotpassword'),




]+ static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

bootcamp/core/forms.py
from django import forms
from django.contrib.auth.models import User


class ProfileForm(forms.ModelForm):

    first_name = forms.CharField(
        widget=forms.TextInput(attrs={'class': 'form-control'}),
        max_length=30,
        required=False)
    last_name = forms.CharField(
        widget=forms.TextInput(attrs={'class': 'form-control'}),
        max_length=30,
        required=False)
    job_title = forms.CharField(
        widget=forms.TextInput(attrs={'class': 'form-control'}),
        max_length=50,
        required=False)
    email = forms.CharField(
        widget=forms.TextInput(attrs={'class': 'form-control'}),
        max_length=75,
        required=False)
    url = forms.CharField(
        widget=forms.TextInput(attrs={'class': 'form-control'}),
        max_length=50,
        required=False)
    location = forms.CharField(
        widget=forms.TextInput(attrs={'class': 'form-control'}),
        max_length=50,
        required=False)

    class Meta:
        model = User
        fields = ['first_name', 'last_name', 'job_title',
                  'email', 'url', 'location', ]


class ChangePasswordForm(forms.ModelForm):
    id = forms.CharField(widget=forms.HiddenInput())
    old_password = forms.CharField(
        widget=forms.PasswordInput(attrs={'class': 'form-control'}),
        label="Old password",
        required=True)

    new_password = forms.CharField(
        widget=forms.PasswordInput(attrs={'class': 'form-control'}),
        label="New password",
        required=True)
    confirm_password = forms.CharField(
        widget=forms.PasswordInput(attrs={'class': 'form-control'}),
        label="Confirm new password",
        required=True)

    class Meta:
        model = User
        fields = ['id', 'old_password', 'new_password', 'confirm_password']

    def clean(self):
        super(ChangePasswordForm, self).clean()
        old_password = self.cleaned_data.get('old_password')
        new_password = self.cleaned_data.get('new_password')
        confirm_password = self.cleaned_data.get('confirm_password')
        id = self.cleaned_data.get('id')
        user = User.objects.get(pk=id)
        if not user.check_password(old_password):
            self._errors['old_password'] = self.error_class([
                'Old password don\'t match'])
        if new_password and new_password != confirm_password:
            self._errors['new_password'] = self.error_class([
                'Passwords don\'t match'])
        return self.cleaned_data

class ContactFormEmail(forms.Form):

    from_email = forms.EmailField(required=True)
    subject = forms.CharField(required=True)
    message = forms.CharField(widget=forms.Textarea)

class ContactForm(forms.Form):

    from_email = forms.EmailField(required=True)
    subject = forms.CharField(required=True)
    message = forms.CharField(widget=forms.Textarea)
    #contact_name = forms.CharField(required=True)
    #contact_email = forms.EmailField(required=True)
    #content = forms.CharField(required=True,widget=forms.Textarea)
    #def __init__(self, *args, **kwargs):
        #super(ContactForm, self).__init__(*args, **kwargs)
        #self.fields['contact_name'].label = "Your name:"
        #self.fields['contact_email'].label = "Your email:"
        #self.fields['content'].label = "Your Message:"


class SearchForm(forms.Form):
    url = forms.URLField()
    depth = forms.IntegerField()
    search = forms.CharField()

bootcamp/core/views.py
import os
import json

from django.shortcuts import get_object_or_404
from django.conf import settings as django_settings
from django.contrib import messages
from django.db.models import Q
from django.contrib.auth import update_session_auth_hash
from django.contrib.auth.decorators import login_required
from django.contrib.auth.models import User
from django.core.paginator import EmptyPage, PageNotAnInteger, Paginator
from django.shortcuts import redirect, render

from bootcamp.core.forms import ChangePasswordForm, ProfileForm, ContactForm,ContactFormEmail
from bootcamp.feeds.views import FEEDS_NUM_PAGES, feeds
from bootcamp.feeds.models import Feed
from bootcamp.articles.models import Article, ArticleComment
from bootcamp.questions.models import Question, Answer
from bootcamp.activities.models import Activity
from bootcamp.messenger.models import Message

#from django.contrib.auth.models import Group
from django.core.mail import send_mail, BadHeaderError
from django.http import HttpResponse, HttpResponseRedirect
from django.core.mail import EmailMessage
from django.template import Context
from django.template.loader import get_template

from django.shortcuts import render_to_response
from django.views.decorators.http import condition
from forms import SearchForm
from django.template import RequestContext
from utils import stream_response

from PIL import Image
import requests

#from pusher import Pusher
#pusher = Pusher(app_id=u'295876', key=u'4b34c484eeb9fe4f4142', secret=u'6b17e2a894fc39296783')
#from django.views.decorators.csrf import csrf_exempt


def home(request):
    if request.user.is_authenticated():
        return feeds(request)
    else:
        return render(request, 'core/cover.html')


@login_required
def network(request):
    users_list = User.objects.filter(is_active=True).order_by('username')
    paginator = Paginator(users_list, 15)
    page = request.GET.get('page')
    try:
        users = paginator.page(page)

    except PageNotAnInteger:
        users = paginator.page(1)

    except EmptyPage:  # pragma: no cover
        users = paginator.page(paginator.num_pages)

    return render(request, 'core/network.html', {'users': users})


@login_required
def profile(request, username):
    page_user = get_object_or_404(User, username=username)
    all_feeds = Feed.get_feeds().filter(user=page_user)
    paginator = Paginator(all_feeds, FEEDS_NUM_PAGES)
    feeds = paginator.page(1)
    from_feed = -1
    if feeds:  # pragma: no cover
        from_feed = feeds[0].id

    feeds_count = Feed.objects.filter(user=page_user).count()
    article_count = Article.objects.filter(create_user=page_user).count()
    article_comment_count = ArticleComment.objects.filter(
        user=page_user).count()
    question_count = Question.objects.filter(user=page_user).count()
    answer_count = Answer.objects.filter(user=page_user).count()
    activity_count = Activity.objects.filter(user=page_user).count()
    messages_count = Message.objects.filter(
        Q(from_user=page_user) | Q(user=page_user)).count()
    data, datepoints = Activity.daily_activity(page_user)
    data = {
        'page_user': page_user,
        'feeds_count': feeds_count,
        'article_count': article_count,
        'article_comment_count': article_comment_count,
        'question_count': question_count,
        'global_interactions': activity_count + article_comment_count + answer_count + messages_count,  # noqa: E501
        'answer_count': answer_count,
        'bar_data': [
            feeds_count, article_count, article_comment_count, question_count,
            answer_count, activity_count],
        'bar_labels': json.dumps('["Feeds", "Articles", "Comments", "Questions", "Answers", "Activities"]'),  # noqa: E501
        'line_labels': datepoints,
        'line_data': data,
        'feeds': feeds,
        'from_feed': from_feed,
        'page': 1
        }

    return render(request, 'core/profile.html', data)

@login_required
def settings(request):
    user = request.user
    if request.method == 'POST':
        form = ProfileForm(request.POST)
        if form.is_valid():
            user.first_name = form.cleaned_data.get('first_name')
            user.last_name = form.cleaned_data.get('last_name')
            user.profile.job_title = form.cleaned_data.get('job_title')
            user.email = form.cleaned_data.get('email')
            user.profile.url = form.cleaned_data.get('url')
            user.profile.location = form.cleaned_data.get('location')
            user.save()
            messages.add_message(request,
                                 messages.SUCCESS,
                                 'Your profile was successfully edited.')

    else:
        form = ProfileForm(instance=user, initial={
            'job_title': user.profile.job_title,
            'url': user.profile.url,
            'location': user.profile.location
            })

    return render(request, 'core/settings.html', {'form': form})


@login_required
def picture(request):
    uploaded_picture = False
    try:
        if request.GET.get('upload_picture') == 'uploaded':
            uploaded_picture = True

    except Exception:  # pragma: no cover
        pass

    return render(request, 'core/picture.html',
                  {'uploaded_picture': uploaded_picture})


@login_required
def coverpicture(request):

    uploaded_cover_picture = False

    try:
        if request.GET.get('cover_upload_picture') == 'uploadedcover':
            uploaded_cover_picture = True

    except Exception:  # pragma: no cover
        pass

    return render(request, 'core/coverpicture.html',
                  {'uploaded_cover_picture': uploaded_cover_picture,
                  })



@login_required
def password(request):
    user = request.user
    if request.method == 'POST':
        form = ChangePasswordForm(request.POST)
        if form.is_valid():
            new_password = form.cleaned_data.get('new_password')
            user.set_password(new_password)
            user.save()
            update_session_auth_hash(request, user)
            messages.add_message(request, messages.SUCCESS,
                                 'Your password was successfully changed.')
            return redirect('password')

    else:
        form = ChangePasswordForm(instance=user)

    return render(request, 'core/password.html', {'form': form})


@login_required
def upload_picture(request):
    try:
        profile_pictures = django_settings.MEDIA_ROOT + '/profile_pictures/'
        if not os.path.exists(profile_pictures):
            os.makedirs(profile_pictures)
        f = request.FILES['picture']
        filename = profile_pictures + request.user.username + '_tmp.jpg'
        with open(filename, 'wb+') as destination:
            for chunk in f.chunks():
                destination.write(chunk)
        im = Image.open(filename)
        width, height = im.size
        if width > 350:
            new_width = 350
            new_height = (height * 350) / width
            new_size = new_width, new_height
            im.thumbnail(new_size, Image.ANTIALIAS)
            im.save(filename)

        return redirect('/settings/picture/?upload_picture=uploaded')

    except Exception as e:
        return redirect('/settings/picture/')


@login_required
def save_uploaded_picture(request):
    try:
        x = int(request.POST.get('x'))
        y = int(request.POST.get('y'))
        w = int(request.POST.get('w'))
        h = int(request.POST.get('h'))
        tmp_filename = django_settings.MEDIA_ROOT + '/profile_pictures/' +\
            request.user.username + '_tmp.jpg'
        filename = django_settings.MEDIA_ROOT + '/profile_pictures/' +\
            request.user.username + '.jpg'
        im = Image.open(tmp_filename)
        cropped_im = im.crop((x, y, w+x, h+y))
        cropped_im.thumbnail((200, 200), Image.ANTIALIAS)
        cropped_im.save(filename)
        os.remove(tmp_filename)

    except Exception:
        pass

    return redirect('/settings/picture/')





@login_required
def cover_upload_picture(request):
    try:
        cover_pictures = django_settings.MEDIA_ROOT + '/cover_pictures/'
        if not os.path.exists(cover_pictures):
            os.makedirs(cover_pictures)
        f = request.FILES['coverpicture']
        filename = cover_pictures + request.user.username + '_tmp.jpg'
        with open(filename, 'wb+') as destination:
            for chunk in f.chunks():
                destination.write(chunk)
        im = Image.open(filename)
        width, height = im.size
        if width > 1000:
            new_width = 1000
            new_height = (height * 1000) / width
            new_size = new_width, new_height
            im.thumbnail(new_size, Image.ANTIALIAS)
            im.save(filename)

        return redirect('/settings/coverpicture/?cover_upload_picture=uploadedcover')

    except Exception as e:
        return redirect('/settings/coverpicture/')


@login_required
def save_cover_uploaded_picture(request):
    try:
       # x = int(request.POST.get('x'))
       # y = int(request.POST.get('y'))
        #w = int(request.POST.get('w'))
       # h = int(request.POST.get('h'))
        tmp_filename = django_settings.MEDIA_ROOT + '/cover_pictures/' +\
            request.user.username + '_tmp.jpg'
        filename = django_settings.MEDIA_ROOT + '/cover_pictures/' +\
            request.user.username + '.jpg'
        im = Image.open(tmp_filename)
        #cropped_im = im.crop((x, y, w+x, h+y))
        #cropped_im.thumbnail((500, 500), Image.ANTIALIAS)
        #cropped_im.save(filename)
        im.save(filename)
        os.remove(tmp_filename)

    except Exception:
        pass

    return redirect('/settings/coverpicture/')

@login_required
def email(request):
    if request.method == 'GET':
        form = ContactFormEmail()
    else:
        form = ContactFormEmail(request.POST)
        if form.is_valid():
            #subject = form.cleaned_data['subject']

bootcamp/core/templates/core/chat.html
{% extends 'base.html' %}
{% load staticfiles %}
{% load i18n %}
{% block title %} Chat{% endblock %}
{% block head %}

    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css"/>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.1.1/jquery.min.js"></script>
    <script src="//js.pusher.com/4.0/pusher.min.js"></script>
    <style>
        .chat
{
    list-style: none;
    margin: 0;
    padding: 0;
}

.chat li
{
    margin-bottom: 10px;
    padding-bottom: 5px;
    border-bottom: 1px dotted #B3A9A9;
}

.chat li.left .chat-body
{
    margin-left: 60px;
}

.chat li.right .chat-body
{
    margin-right: 60px;
}


.chat li .chat-body p
{
    margin: 0;
    color: #777777;
}

.panel .slidedown .glyphicon, .chat .glyphicon
{
    margin-right: 5px;
}

.panel-body
{
    overflow-y: scroll;
    height: 250px;
}

::-webkit-scrollbar-track
{
    -webkit-box-shadow: inset 0 0 6px rgba(0,0,0,0.3);
    background-color: #F5F5F5;
}

::-webkit-scrollbar
{
    width: 12px;
    background-color: #F5F5F5;
}

::-webkit-scrollbar-thumb
{
    -webkit-box-shadow: inset 0 0 6px rgba(0,0,0,.3);
    background-color: #555;
}

    </style>
{% endblock head %}
{% block main %}

        <div class="container">
    <div class="row">
        <div class="col-md-12">
            <div class="panel panel-primary">
                <div class="panel-heading">
                    <span class="glyphicon glyphicon-comment"></span> Chat
                    
                </div>
                <div class="panel-body">
                    <ul class="chat" id="chat">
                    </ul>
                </div>
                <div class="panel-footer">
                    <div class="input-group">
                        <input id="btn-input" class="form-control input-sm" placeholder="Type your message here..." type="text">
                        <span class="input-group-btn">
                            <button class="btn btn-warning btn-sm" id="btn-chat">
                                Send</button>
                        </span>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
<script>
    var pusher = new Pusher('4b34c484eeb9fe4f4142');
    var my_channel = pusher.subscribe('a_channel');
    my_channel.bind("an_event", function (data) {
        var new_message = `<li class="left clearfix"><span class="chat-img pull-left">
                            <img src="http://placehold.it/50/55C1E7/fff&amp;text=`+data.name+`" alt="User Avatar" class="img-circle">
                        </span>
                            <div class="chat-body clearfix">
                                <div class="header">
                                    <strong class="primary-font">`+data.name+`</strong> <small class="pull-right text-muted">
                                </div>
                                <p>
                                   `+data.message+`
                                </p>
                            </div>
                        </li>`;
    $('#chat').append(new_message);
    });

    $(document).ready(function(){
        $("#btn-chat").click(function(){
             var message = $('#btn-input').val();
             
            $.post({
                url: '/chat/',
                data: {
                'message': message
                },
                success: function (data) {
               
                    $('#btn-input').val('');
                
                }
            });

        })
    })
   
</script>
{% endblock main %}

bootcamp/core/templates/core/contact.html
{% extends 'base.html' %}
{% load staticfiles %}
{% load i18n %}
{% block title %} Invite-User{% endblock %}
{% block main %}
<h1>Invite-Forward Articles to User Form</h1>
<form method="post">
    {% csrf_token %}
    {{ form }}
    <div class="form-actions">
      <button type="submit" class="btn btn-primary pull-right btn-compose">Send</button>
    </div>
</form>
<style>form {
    width: 50%;
}input#id_from_email, input#id_subject, textarea#id_message {
    width: 100%;
    z-index: 100;
}</style>
{% endblock main %}

bootcamp/core/templates/core/cover.html
{% extends 'base.html' %}
{% load staticfiles %}
{% load i18n %}

{% block head %}
  <link href="{% static 'css/cover.css' %}" rel="stylesheet">
  <style>body {
  background-color: #006389;
}

.cover {
  width: 400px;
  height: 400px;
  position: fixed;
  margin-left: -200px;
  margin-top: -200px;
  top: 50%;
  left: 50%;
}

.logo {
  margin: 0;
  font-size: 3em;
  font-weight: 200;
  font-family: "Audiowide", cursive;
  color: #92c35e;
  text-align: center;
  text-shadow: 1px 1px 0 #333333;
  line-height: 70px;
}

.login {
  background-color: #f6f6f6;
  width: 100%;
  height: 330px;
  border-radius: 7px;
}

.login {
  padding: 10px 20px;
}

.login form {
  margin-top: 20px;
}</style>
{% endblock head %}

{% block body %}
<!--  <a href="https://github.com/vitorfs/bootcamp"><img style="position: absolute; top: 0; right: 0; border: 0;" src="https://camo.githubusercontent.com/e7bbb0521b397edbd5fe43e7f760759336b5e05f/68747470733a2f2f73332e616d617a6f6e6177732e636f6d2f6769746875622f726962626f6e732f666f726b6d655f72696768745f677265656e5f3030373230302e706e67" alt="Fork me on GitHub" data-canonical-src="https://s3.amazonaws.com/github/ribbons/forkme_right_green_007200.png"></a>-->
  <div class="cover">
    <h1 class="logo">Tweet App</h1>
    {% if form.non_field_errors %}
      {% for error in form.non_field_errors %}
        <div class="alert alert-danger alert-dismissable">
          <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
          {{ error }}
        </div>
      {% endfor %}
    {% endif %}
    <div class="login">
      <h2>{% trans 'Log in' %}</h2>
      <form method="post" action="{% url 'login' %}" role="form">
        {% csrf_token %}
        <div class="form-group{% if form.username.errors %} has-error{% endif %}">
          <label for="username">{% trans 'Username' %}</label>
          <input type="text" class="form-control" id="username" name="username">
          {% for error in form.username.errors %}
            <label class="control-label">{{ error }}</label>
          {% endfor %}
        </div>
        <div class="form-group{% if form.password.errors %} has-error{% endif %}">
          <label for="password">{% trans 'Password' %}</label>
          <input type="password" class="form-control" id="password" name="password">
          {% for error in form.password.errors %}
            <label class="control-label">{{ error }}</label>
          {% endfor %}
        </div>
        <div class="form-group">
          <button type="submit" class="btn btn-default">{% trans 'Log in' %}</button>
          <a href="{% url 'signup' %}" class="btn btn-link">{% trans 'Sign up' %}</a>
        </div>
      </form>
    </div>
  </div>
{% endblock body %}

bootcamp/core/templates/core/coverpicture.html
{% extends 'base.html' %}

{% load i18n static %}

{% block title %}{% trans 'Account Settings' %}{% endblock %}

{% block head %}
  <link href="{% static 'css/jquery.Jcrop.min.css' %}" rel="stylesheet">
  <script src="{% static 'js/jquery.Jcrop.min.js' %}"></script>
  <script src="{% static 'js/coverpicture.js' %}"></script>
  <style>.modal-dialog {
    width: 1000px;
}</style>
{% endblock head %}

{% block main %}
  <div class="page-header">
    <h1>{% trans 'Account Settings' %}</h1>
  </div>
  <div class="row" style="margin-top: 2em">
    <div class="col-md-3">
      {% include 'core/partial_settings_menu.html' with active='coverpicture' %}
    </div>
    <div class="col-md-9">
      {% if messages %}
        {% for message in messages %}
          <div class="alert alert-success alert-dismissable">
            <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
            {{ message }}
          </div>
        {% endfor %}
      {% endif %}

      <h3 style="margin-top: 0">{% trans 'Change Cover Picture' %}</h3>
      <img src="/staticfiles/img/cover_pictures/{{ user.username }}.jpg" style="border-radius: 5px; margin-bottom: 1em;">
      <form enctype="multipart/form-data" method="post" action="{% url 'cover_upload_picture' %}" id="cover-picture-upload-form">
        {% csrf_token %}
        <input type="file" name="coverpicture" style="display: none">
        <button type="button" class="btn btn-default" id="btn-cover-upload-picture">{% trans 'Upload new picture' %}</button>
      </form>
      {% if uploaded_cover_picture %}
        <form method="post" action="{% url 'save_cover_uploaded_picture' %}">
          {% csrf_token %}
          <div class="modal fade" id="modal-cover-upload-picture">
            <div class="modal-dialog">
              <div class="modal-content">
                <div class="modal-header">
                  <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
                  <h4 class="modal-title">{% trans 'Crop Picture' %}</h4>
                </div>
                <div class="modal-body">
                  <div class="selected-picture">
                    <p>{% trans 'Crop the profile picture and then click on the' %} <strong>{% trans 'Save Picture' %}</strong> {% trans 'button' %}</p>
                    <!--<img src="/staticfiles/img/cover_pictures/{{ user.username }}_tmp.jpg?_={% now 'U' %}" id="crop-picture">-->
                    <img src="/staticfiles/img/cover_pictures/{{ user.username }}_tmp.jpg?_={% now 'U' %}">
                    <input type="hidden" id="x" name="x" />
                    <input type="hidden" id="y" name="y" />
                    <input type="hidden" id="w" name="w" />
                    <input type="hidden" id="h" name="h" />
                  </div>
                  <script type="text/javascript">
                    $(function () {
                      $("#modal-cover-upload-picture").modal();
                      window.history.pushState("", "", "http://tweetapp.pythonanywhere.com/settings/coverpicture/");
                    });
                  </script>
                </div>
                <div class="modal-footer">
                  <button type="button" class="btn btn-default" data-dismiss="modal">{% trans 'Close' %}</button>
                  <button type="submit" class="btn btn-primary">{% trans 'Save changes' %}</button>
                </div>
              </div>
            </div>
          </div>
        </form>
      {% endif %}



    </div>
  </div>
{% endblock main %}

bootcamp/core/templates/core/forgotpassword.html
{% load i18n %}
<!DOCTYPE html>
<html>
<head>
    <title></title>
</head>
<body>
    <form method="post">{% csrf_token %}
        <div>
            {{ form.email.errors }}
            <label for="id_email">{% trans 'Email address:' %}</label>
            {{ form.email }}
        </div>
        <input type="submit" value="{% trans 'Reset my password' %}" />
    </form>
</body>
</html>

bootcamp/core/templates/core/partial_settings_menu.html
{% load i18n %}
<div class="list-group">
  <a href="{% url 'settings' %}" class="list-group-item{% if active == 'profile' %} active{% endif %}">{% trans 'Profile' %}</a>
  <a href="{% url 'picture' %}" class="list-group-item{% if active == 'picture' %} active{% endif %}">{% trans 'Picture' %}</a>
  <a href="{% url 'coverpicture' %}" class="list-group-item{% if active == 'coverpicture' %} active{% endif %}">{% trans 'CoverPicture' %}</a>
  <a href="{% url 'password' %}" class="list-group-item{% if active == 'password' %} active{% endif %}">{% trans 'Password' %}</a>
</div>

bootcamp/core/templates/core/thankyou.html
{% extends 'base.html' %}
{% load staticfiles %}
{% load i18n %}
{% block title %} Email-Contact -{{ block.super }}{% endblock %}
{% block main %}

<h1>Articles Shared </h1>

{% endblock main %}